-- 备件商品订单主附表（MySQL 增量迁移）

CREATE TABLE IF NOT EXISTS spare_part_order (
    id                      BIGINT        NOT NULL COMMENT '主键',
    order_no                VARCHAR(64)   NOT NULL COMMENT '业务订单号（唯一）',
    client_user_id          BIGINT        NOT NULL COMMENT '买家用户 ID（client 用户）',
    merchant_user_id        BIGINT        NOT NULL COMMENT '卖家用户 ID（店铺所有者）',
    merchant_profile_id     BIGINT        NULL COMMENT '店铺资料 ID 快照',
    merchant_name           VARCHAR(128)  NULL COMMENT '店铺名称快照',
    order_status            VARCHAR(32)   NOT NULL COMMENT '订单状态',
    pay_status              VARCHAR(32)   NOT NULL COMMENT '支付状态：pending/paid/cancelled',
    total_amount_cents      INT           NOT NULL COMMENT '订单总金额（分）',
    buyer_remark            VARCHAR(512)  NULL COMMENT '买家订单备注',
    shipping_address_json   VARCHAR(1024) NOT NULL COMMENT '收货地址快照（JSON）',
    logistics_company       VARCHAR(64)   NULL COMMENT '物流公司名称',
    logistics_tracking_no   VARCHAR(128)  NULL COMMENT '物流单号',
    logistics_image_urls    VARCHAR(2048) NULL COMMENT '物流凭证图片 URL 列表（JSON 数组）',
    pay_time                DATETIME      NULL COMMENT '支付完成时间',
    ship_time               DATETIME      NULL COMMENT '发货时间',
    receive_time            DATETIME      NULL COMMENT '确认收货时间',
    auto_receive_deadline   DATETIME      NULL COMMENT '自动确认收货截止时间',
    review_time             DATETIME      NULL COMMENT '评价完成时间',
    cancel_time             DATETIME      NULL COMMENT '取消时间',
    create_time             DATETIME      NOT NULL COMMENT '创建时间',
    update_time             DATETIME      NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_spare_part_order_no (order_no),
    KEY idx_spare_part_order_client_status (client_user_id, order_status, create_time),
    KEY idx_spare_part_order_merchant_status (merchant_user_id, order_status, create_time),
    KEY idx_spare_part_order_pay_status (pay_status),
    KEY idx_spare_part_order_auto_receive (order_status, auto_receive_deadline)
) COMMENT '备件商品订单主表';

CREATE TABLE IF NOT EXISTS spare_part_order_item (
    id                  BIGINT         NOT NULL COMMENT '主键',
    order_id            BIGINT         NOT NULL COMMENT '关联订单主表 ID',
    source_listing_id   BIGINT         NULL COMMENT '原商品 listing ID（仅追溯）',
    source_sku_id       BIGINT         NULL COMMENT '原 SKU ID（仅追溯）',
    product_title       VARCHAR(128)   NOT NULL COMMENT '商品标题快照',
    cover_image_url     VARCHAR(512)   NULL COMMENT '商品封面图快照',
    sku_spec_labels     VARCHAR(1024)  NULL COMMENT '规格标签快照（JSON 数组）',
    brand_name          VARCHAR(128)   NULL COMMENT '品牌名称快照',
    category_name       VARCHAR(128)   NULL COMMENT '分类名称快照',
    spare_part_type     VARCHAR(64)    NULL COMMENT '备件类型快照',
    equipment_model     VARCHAR(128)   NULL COMMENT '型号快照',
    unit_price_cents    INT            NOT NULL COMMENT '成交单价（分）',
    quantity            INT            NOT NULL COMMENT '购买数量',
    subtotal_cents      INT            NOT NULL COMMENT '小计金额（分）',
    create_time         DATETIME       NOT NULL COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_spare_part_order_item_order (order_id)
) COMMENT '备件商品订单明细（商品快照）';
