-- 平台保险签约：配置 + 订单（流程开关见 engineering_sign_fee_config）
CREATE TABLE IF NOT EXISTS engineering_insurance_sign_config (
    id                          BIGINT         NOT NULL COMMENT '主键（单行配置，固定为 1）',
    enabled                     TINYINT        NOT NULL DEFAULT 1 COMMENT '是否启用保险签约：0-否 1-是',
    sign_service_fee_cents      INT            NOT NULL COMMENT '签约服务费（分）',
    evidence_fee_cents          INT            NOT NULL COMMENT '存证费（分）',
    platform_initiate_hours     INT            NOT NULL COMMENT '平台发起电子签时限（小时）',
    platform_name               VARCHAR(128)   NOT NULL DEFAULT '平台' COMMENT '合同填表平台名称',
    contract_file_id            BIGINT         NULL COMMENT '保险合同 PDF 模板文件 ID',
    buyer_sign_page             INT            NULL COMMENT '用户手写签名-页码（从 1 起）',
    buyer_sign_x                DECIMAL(10,2)  NULL COMMENT '用户手写签名-X 坐标(pt)',
    buyer_sign_y                DECIMAL(10,2)  NULL COMMENT '用户手写签名-Y 坐标(pt)',
    buyer_sign_width            INT            NULL COMMENT '用户手写签名-宽度(pt)',
    buyer_sign_height           INT            NULL COMMENT '用户手写签名-高度(pt)',
    create_time                 DATETIME       NOT NULL COMMENT '创建时间',
    update_time                 DATETIME       NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
) COMMENT '平台保险签约业务配置（费用与合同模板）';

CREATE TABLE IF NOT EXISTS engineering_insurance_sign_order (
    id                              BIGINT         NOT NULL COMMENT '主键',
    order_no                        VARCHAR(64)    NOT NULL COMMENT '业务订单号（SGI 前缀）',
    insurance_product_id            BIGINT         NOT NULL COMMENT '保险产品 ID',
    product_title                   VARCHAR(128)   NOT NULL COMMENT '保险产品标题快照',
    applicant_client_user_id        BIGINT         NOT NULL COMMENT '申请人用户 ID',
    applicant_name                  VARCHAR(64)    NOT NULL COMMENT '申请人姓名',
    applicant_phone                 VARCHAR(32)    NOT NULL COMMENT '申请人手机号',
    province                        VARCHAR(64)    NOT NULL COMMENT '省',
    city                            VARCHAR(64)    NOT NULL COMMENT '市',
    district                        VARCHAR(64)    NOT NULL COMMENT '区/县',
    address_detail                  VARCHAR(512)   NOT NULL COMMENT '详细地址',
    agreed_price_cents              INT            NOT NULL DEFAULT 0 COMMENT '约定保费/预估价快照（分）',
    remark                          VARCHAR(512)   NULL COMMENT '备注',
    sign_service_fee_cents          INT            NOT NULL COMMENT '签约服务费快照（分）',
    evidence_fee_cents              INT            NOT NULL COMMENT '存证费快照（分）',
    total_fee_cents                 INT            NOT NULL COMMENT '应付合计（分）',
    ess_enabled                     TINYINT        NOT NULL DEFAULT 0 COMMENT '是否走电子签（建单快照，取自全局配置）',
    status                          VARCHAR(32)    NOT NULL COMMENT '订单状态（复用 SignOrderStatus）',
    pay_status                      VARCHAR(32)    NOT NULL COMMENT '支付状态 pending/paid/refunded',
    platform_initiate_deadline      DATETIME       NULL COMMENT '平台发起电子签截止时间',
    ess_flow_id                     VARCHAR(128)   NULL COMMENT '腾讯电子签流程 Id',
    ess_scheme_url                  VARCHAR(1024)  NULL COMMENT '用户签署短链/小程序 path',
    pay_time                        DATETIME       NULL COMMENT '支付成功时间',
    sign_finish_time                DATETIME       NULL COMMENT '签署完成时间',
    refund_time                     DATETIME       NULL COMMENT '退款完成时间',
    create_time                     DATETIME       NOT NULL COMMENT '创建时间',
    update_time                     DATETIME       NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_eng_insurance_sign_order_no (order_no),
    KEY idx_eng_ins_sign_order_applicant (applicant_client_user_id, create_time),
    KEY idx_eng_ins_sign_order_product (insurance_product_id, create_time),
    KEY idx_eng_ins_sign_order_status (status, create_time),
    KEY idx_eng_ins_sign_order_ess_flow (ess_flow_id)
) COMMENT '平台保险签约订单';
