DEPLOY_HOST=1.14.48.236
DEPLOY_USER=root
DEPLOY_PORT=22
DEPLOY_DIR=/opt/deadman
APP_PORT=8080
PACKAGE_PROFILE=prod
FRONTEND_DIST="/Users/moyang/make_the_fucking_money/money/Engineering Information/deadman-admin-ui/dist.zip"
