-- deadman-plugin-identity 集成测试用 H2

CREATE TABLE IF NOT EXISTS plugin_identity_person (
    id                    BIGINT        NOT NULL,
    realm                 VARCHAR(32)   NOT NULL,
    subject_id            BIGINT        NOT NULL,
    real_name             VARCHAR(64)   NOT NULL,
    id_card_no            VARCHAR(18)   NOT NULL,
    gender                SMALLINT      NOT NULL,
    birth_date            DATE          NOT NULL,
    id_card_front_file_id BIGINT        NOT NULL,
    id_card_back_file_id  BIGINT        NOT NULL,
    face_file_id          BIGINT        NOT NULL,
    liveness_score        DOUBLE,
    liveness_request_id   VARCHAR(64),
    match_score           DOUBLE,
    compare_request_id    VARCHAR(64),
    status                VARCHAR(16)   NOT NULL,
    reject_reason         VARCHAR(512),
    verified_time         TIMESTAMP     NOT NULL,
    is_deleted            SMALLINT      NOT NULL DEFAULT 0,
    create_time           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version               INT           NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_plugin_identity_person_subject UNIQUE (realm, subject_id)
);

CREATE TABLE IF NOT EXISTS plugin_identity_enterprise (
    id                     BIGINT        NOT NULL,
    realm                  VARCHAR(32)   NOT NULL,
    subject_id             BIGINT        NOT NULL,
    enterprise_name        VARCHAR(128)  NOT NULL,
    credit_code            VARCHAR(32)   NOT NULL,
    address                VARCHAR(256)  NOT NULL,
    legal_person_name      VARCHAR(64)   NOT NULL,
    legal_id_card_no       VARCHAR(18)   NOT NULL,
    license_file_id        BIGINT        NOT NULL,
    legal_id_front_file_id BIGINT        NOT NULL,
    legal_id_back_file_id  BIGINT        NOT NULL,
    legal_face_file_id     BIGINT        NOT NULL,
    liveness_score         DOUBLE,
    liveness_request_id    VARCHAR(64),
    match_score            DOUBLE,
    compare_request_id     VARCHAR(64),
    status                 VARCHAR(16)   NOT NULL,
    reject_reason          VARCHAR(512),
    verified_time          TIMESTAMP     NOT NULL,
    is_deleted             SMALLINT      NOT NULL DEFAULT 0,
    create_time            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version                INT           NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_plugin_identity_enterprise_subject UNIQUE (realm, subject_id)
);
