-- deadman-plugin-identity 个人实名与企业认证（MySQL 8+）

CREATE TABLE IF NOT EXISTS plugin_identity_person (
    id                    BIGINT        NOT NULL COMMENT '主键',
    realm                 VARCHAR(32)   NOT NULL COMMENT '业务域',
    subject_id            BIGINT        NOT NULL COMMENT '业务主体 ID',
    real_name             VARCHAR(64)   NOT NULL COMMENT '真实姓名',
    id_card_no            VARCHAR(18)   NOT NULL COMMENT '身份证号',
    gender                SMALLINT      NOT NULL COMMENT '性别：1-男，2-女',
    birth_date            DATE          NOT NULL COMMENT '出生日期',
    id_card_front_file_id BIGINT        NOT NULL COMMENT '身份证人像面文件 ID',
    id_card_back_file_id  BIGINT        NOT NULL COMMENT '身份证国徽面文件 ID',
    face_file_id          BIGINT        NOT NULL COMMENT '现场人脸文件 ID',
    liveness_score        DOUBLE                 COMMENT '活体分数',
    liveness_request_id   VARCHAR(64)            COMMENT '活体检测请求 ID',
    match_score           DOUBLE                 COMMENT '人脸相似度',
    compare_request_id    VARCHAR(64)            COMMENT '人脸比对请求 ID',
    status                VARCHAR(16)   NOT NULL COMMENT 'PASSED / REJECTED',
    reject_reason         VARCHAR(512)           COMMENT '未通过原因',
    verified_time         TIMESTAMP     NOT NULL COMMENT '最近一次判定时间',
    is_deleted            SMALLINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version               INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_plugin_identity_person_subject (realm, subject_id),
    KEY idx_plugin_identity_person_status (status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='个人实名认证';

CREATE TABLE IF NOT EXISTS plugin_identity_enterprise (
    id                     BIGINT        NOT NULL COMMENT '主键',
    realm                  VARCHAR(32)   NOT NULL COMMENT '业务域',
    subject_id             BIGINT        NOT NULL COMMENT '业务主体 ID',
    enterprise_name        VARCHAR(128)  NOT NULL COMMENT '企业名称',
    credit_code            VARCHAR(32)   NOT NULL COMMENT '统一社会信用代码',
    address                VARCHAR(256)  NOT NULL COMMENT '企业地址',
    legal_person_name      VARCHAR(64)   NOT NULL COMMENT '法人姓名',
    legal_id_card_no       VARCHAR(18)   NOT NULL COMMENT '法人身份证号',
    license_file_id        BIGINT        NOT NULL COMMENT '营业执照文件 ID',
    legal_id_front_file_id BIGINT        NOT NULL COMMENT '法人身份证人像面文件 ID',
    legal_id_back_file_id  BIGINT        NOT NULL COMMENT '法人身份证国徽面文件 ID',
    legal_face_file_id     BIGINT        NOT NULL COMMENT '法人现场人脸文件 ID',
    liveness_score         DOUBLE                 COMMENT '法人活体分数',
    liveness_request_id    VARCHAR(64)            COMMENT '法人活体检测请求 ID',
    match_score            DOUBLE                 COMMENT '法人人脸相似度',
    compare_request_id     VARCHAR(64)            COMMENT '法人人脸比对请求 ID',
    status                 VARCHAR(16)   NOT NULL COMMENT 'PASSED / REJECTED',
    reject_reason          VARCHAR(512)           COMMENT '未通过原因',
    verified_time          TIMESTAMP     NOT NULL COMMENT '最近一次判定时间',
    is_deleted             SMALLINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    create_time            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version                INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_plugin_identity_enterprise_subject (realm, subject_id),
    KEY idx_plugin_identity_enterprise_status (status, is_deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='企业认证';
